export const METHOD = {
    GET: 'GET',
    POST: 'POST'
}

export const STATUSCODE = {
    SUCCESS: 200,
    CREATED: 201,
    BADREQUEST: 400,
    FORBIDDEN: 401,
    INTERNALERRORS: 500,
    SESSIONTIMEOUT: 408
}