

export const START_LOADING_TRANDING_MOVIES = 'START_LOADING_TRANDING_MOVIES'
export const FAILED_TRANDING_MOVIES = 'FAILED_TRANDING_MOVIES'
export const RECEIVED_TRANDING_MOVIES = 'RECEIVED_TRANDING_MOVIES'

export const START_LOADING_POPULAR_MOVIES = 'START_LOADING_POPULAR_MOVIES'
export const FAILED_POPULAR_MOVIES = 'FAILED_POPULAR_MOVIES'
export const RECEIVED_POPULAR_MOVIES = 'RECEIVED_POPULAR_MOVIES'

export const START_LOADING_MOVIE_DETAILS = 'START_LOADING_MOVIE_DETAILS'
export const FAILED_MOVIE_DETAILS = 'FAILED_MOVIE_DETAILS'
export const RECEIVED_MOVIE_DETAILS = 'RECEIVED_MOVIE_DETAILS'

export const START_LOADING_CASTS = 'START_LOADING_CASTS'
export const FAILED_CASTS = 'FAILED_CASTS'
export const RECEIVED_CASTS = 'RECEIVED_CASTS'

export const START_LOADING_SEARCH = 'START_LOADING_SEARCH'
export const FAILED_SEARCH = 'FAILED_SEARCH'
export const RECEIVED_SEARCH = 'RECEIVED_SEARCH'
